<a href="https://colab.research.google.com/github/topchaebol/006762/blob/master/1_%EB%84%98%ED%8C%8C%EC%9D%B4_%EC%88%AB%EC%9E%90_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 배열 선언하기

# 자료형 선언하기

In [1]:
import numpy as np
b = np.array([1,2,3], dtype=np.float)
b

array([1., 2., 3.])

In [2]:
b.dtype

dtype('float64')

# 넘파이 배열속성

In [3]:
c = np.array([b, b+9, b+18])
c.ndim


2

In [4]:
c.itemsize

8

In [5]:
c.size

9

In [6]:
c.nbytes

72

In [7]:
c

array([[ 1.,  2.,  3.],
       [10., 11., 12.],
       [19., 20., 21.]])

In [8]:
c.T

array([[ 1., 10., 19.],
       [ 2., 11., 20.],
       [ 3., 12., 21.]])