<a href="https://colab.research.google.com/github/topchaebol/006762/blob/master/2_%EB%84%98%ED%8C%8C%EC%9D%B4%EB%A1%9C_%EC%88%AB%EC%9E%90%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 유니버셜
단항 유니버셜, 이항 유니버셜 함수 
값이 1개, 절대값, 제곱, 제곱근, 지수, 반올림, 나눗셈, 나머지 계산, 삼각함수
값이 2개, 사칙연산과 비교연산 등

In [13]:
import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [14]:
b = np.array([a,a*3,a+12])
b

array([[ 0,  1,  2,  3],
       [ 0,  3,  6,  9],
       [12, 13, 14, 15]])

In [18]:
np.hsplit(b, 0)

ZeroDivisionError: ignored

In [19]:
np.argmax(b)

11

In [20]:
b.T

array([[ 0,  0, 12],
       [ 1,  3, 13],
       [ 2,  6, 14],
       [ 3,  9, 15]])

In [0]:
b = b.T

In [26]:
b

array([[ 0,  0, 12],
       [ 1,  3, 13],
       [ 2,  6, 14],
       [ 3,  9, 15]])

In [29]:
d = b.copy()
d

array([[ 0,  0, 12],
       [ 1,  3, 13],
       [ 2,  6, 14],
       [ 3,  9, 15]])

In [31]:
d is b

False

In [32]:
d.base is b

False