<a href="https://colab.research.google.com/github/topchaebol/006762/blob/master/%EC%A3%BC%ED%94%BC%ED%84%B0_%EB%85%B8%ED%8A%B8%EB%B6%81_%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np;
np.arange(5)

array([0, 1, 2, 3, 4])

In [0]:
a= np.array([np.arange(5), np.arange(5)])

In [16]:
a[0, 0]

0

In [17]:
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [18]:
a * 2

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])